[package]
name = "escrow"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
logging = []

[lints]
workspace = true

[dependencies]
bytemuck.workspace = true
typhoon.workspace = true
typhoon-token.workspace = true
escrow-interface.workspace = true

[build-dependencies]
typhoon-idl-generator.workspace = true

[dev-dependencies]
escrow-interface = { workspace = true, features = ["client"] }
litesvm = "0.9"
litesvm-token = "0.9"
solana-keypair = "3.1"
solana-native-token = "3.0"
solana-signer = "3.0"
solana-transaction = "3.0"
spl-associated-token-account-client = "2.0.0"
