[package]
name = "star_frame"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
no_entrypoint = []
idl = ["star_frame/idl"]

[dependencies]
star_frame = { version = "0.26.2", features = ["aggressive_inline"] }
borsh = "1.5"
bytemuck = "1.24"
