[package]
name = "misc-interface"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]

[features]
client = [
    "dep:solana-address",
    "dep:solana-instruction",
    "dep:typhoon-instruction-builder",
]

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
const-crypto = "0.3.0"
solana-instruction = { workspace = true, optional = true }
solana-address = { workspace = true, optional = true }
typhoon-instruction-builder = { workspace = true, optional = true }
typhoon.workspace = true

[package.metadata.typhoon.builder-dependencies]
misc = { path = "../program" }
